services:
  inlaudo-web:
    image: ${DOCKER_IMAGE:-wallesonnn/inlaudo}:${DOCKER_TAG:-latest}
    container_name: inlaudo-web
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "app=inlaudo"
      - "domain=inlaudo.pro"
      - "service=inlaudo-web"
    networks:
      - proxy

networks:
  proxy:
    external: true
