services:
  inlaudo-web:
    image: ${DOCKER_IMAGE:-wallesonnn/inlaudo}:${DOCKER_TAG:-latest}
    container_name: inlaudo-web
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "app=inlaudo"
      - "domain=inlaudo.pro"
      - "service=inlaudo-web"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.inlaudo.rule=Host(`inlaudo.pro`)"
      - "traefik.http.routers.inlaudo.entrypoints=websecure"
      - "traefik.http.routers.inlaudo.tls=true"
      - "traefik.http.routers.inlaudo.tls.certresolver=lets-encrypt"
      - "traefik.http.services.inlaudo.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
